### ISSUE TITLE
How can i only use cpu for inference in torchserve?

### ISSUE THREAD

**Issue by WxyStudent** [pytorch/serve#1018]

**Comment by HamidShojanazeri** [comment]
@WxyStudent in the [config.properties](https://github.com/pytorch/serve/blob/master/docs/configuration.md#limit-gpu-usage) you can set the number_of_gpus =0.

**Comment by ozancaglayan** [comment]
Is there a solution for deploying one model on CPU but some other(s) on GPUs, other than modifying the BaseHandler so that it selectively sets the `device` depending on some other config params?

**Comment by msaroufim** [comment]
You could have multiple docker containers each with their own config.properties. Would that work?

**Comment by ozancaglayan** [comment]
i thought about it as well: lets remove docker from the equation, you are basically suggesting to run one torchserve instance for models that will run on vCPUs, and another for models that should be launched on GPUs. For the former, I add number_of_gpus=0 to ts config.

But is there a way to orchestrate things so that both APIs are accessible from the same IP:port? Otherwise, one should expose two different APIs which is a bit counterintuitive.

What if we add `useGpu: bool` to

models={}

dictionary in config.properties, and this somehow forces `gpu_id` to be None, instead of integers in the handlers?

**Comment by agunapal** [comment]
The following commands work

Use GPU
```
docker run --rm -it --gpus all -p 8080:8080 -p 8081:8081 -p 8082:8082 -v $(pwd)/model_store:/home/model-server/model-store pytorch/torchserve:latest-gpu

```
Use CPU

```
docker run --rm -it -p 8080:8080 -p 8081:8081 -p 8082:8082 -v $(pwd)/model_store:/home/model-server/model-store pytorch/torchserve:latest-gpu

```

**Comment by thhung** [comment]
> The following commands work
> 
> Use GPU
> 
> ```
> docker run --rm -it --gpus all -p 8080:8080 -p 8081:8081 -p 8082:8082 -v $(pwd)/model_store:/home/model-server/model-store pytorch/torchserve:latest-gpu
> ```
> 
> Use CPU
> 
> ```
> docker run --rm -it -p 8080:8080 -p 8081:8081 -p 8082:8082 -v $(pwd)/model_store:/home/model-server/model-store pytorch/torchserve:latest-gpu
> ```

Thanks @agunapal . Unfortunately, I cannot use docker in my environment so I use torchserve directly without docker. I tried to make it not use GPU by ts config file. However, it didn't work.
