### ISSUE TITLE
docker instance with torch serve error (running the examples provided)

### ISSUE THREAD

**Issue by ytsheng** [pytorch/serve#1246]
## Context
Hi Team,

I am really trying to understand serving a torchserve instance with docker. Therefore, I ran the documentation examples on torchserve and docker. Unfortunately they are not working for me. To be clear running torchserve locally works, but not with docker. 

## Your Environment

* torchserve version: 0.4.0
* torch-model-archiver version: 0.4.0b20210521
* torch version: 1.8.1
* torchvision version [if any]:  0.9.1
* torchtext version [if any]: 0.5.0
* torchaudio version [if any]: 0.8.1
* java version: (it was empty when I executed `print_env_info.py`
* Operating System and version:
OS: Ubuntu 20.04.1 LTS
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: N/A
CMake version: version 3.16.3

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: just using the ones provided
* What kind of model is it e.g. vision, text, audio?: vision
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: local model
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
```
inference_address=http://127.0.0.1:8443
management_address=http://127.0.0.1:8444
metrics_address=http://127.0.0.1:8445
number_of_gpu=1
install_py_dep_per_model=true
model_store=/home/model-server/model-store
```
* Link to your project [if any]:

## Expected Behavior
docker with the examples provided should work. 

## Current Behavior
Running the following in sequence:
`docker run --rm -it -p 8334:8334 -p 8444:8444 -p 8445:8445 --name mar -v $(pwd)/model-store:/home/model-server/model-store -v $(pwd)/examples:/home/model-server/examples -v $(pwd)/config.properties:/home/model-server/config.properties pytorch/torchserve:latest`
`docker ps`
`docker exec -it <container_name> /bin/bash`
`curl -o /home/model-server/examples/image_classifier/densenet161-8d451a50.pth https://download.pytorch.org/models/densenet161-8d451a50.pth`

When I ran the above command to download the model file, it was running into issues saying `Warning: Permission Denied` Also, I cannot save any file/folder into the model-server directory nor model-server/examples directory.

## Possible Solution
I ran `ls -la` in the model-server directory. And saw that the model-store is owned by user root, and group root. I did see that the Dockerfile changed the owner to model-server as opposed to root with chmod -R model-server <model-server-directory>([link](https://hub.docker.com/layers/pytorch/torchserve/latest/images/sha256-3c290c60cb89bca38fbf1d6a36ea99554b3dbb9d32cb89ed434828c5b3fd2c73?context=explore)). So I am not sure what is going on here..

## Steps to Reproduce
See above

## Another Issue:
I ran the build docker script with:
1. `./build_image.sh -bt dev -g -cv cu102` and then ran 
2. `docker run --rm -it -p 8334:8334 -p 8444:8444 -p 8445:8445 --name mar -v $(pwd)/model-store:/home/model-server/model-store -v $(pwd)/examples:/home/model-server/examples -v $(pwd)/config.properties:/home/model-server/config.properties pytorch/dev:latest`

I am getting an error saying that 

`/usr/local/bin/dockerd-entrypoint.sh: line 8: torchserve: command not found`

I think something is really wrong because the build script should have installed torchserve. My current torchserve package is installed in a local conda environment..

**Comment by msaroufim** [comment]
When you're working with Docker it's easier to do everything you need to do with `Dockerfile` so ideally you should never need to actually log into it except to read logs (The VS code Docker extension is amazing for this kind of debugging)

So for example here instead of curling your model weights to the docker instance just copy over the model https://gist.github.com/msaroufim/6e4a61e714410a4b6d9901e0647e8270#file-gistfile1-txt-L100

`COPY densenet161-8d451a50.pth /home/model-server/model-store/densenet161-8d451a50.pth`

The other thing to keep in mind is torchserve actually packages everything up into `mar` files so you need to either package up your model locally and then upload the mar file using COPY

or you can use a Docker RUN command to create the mar file on the docker instance

So for example from the README you can do this:

`torch-model-archiver --model-name densenet161 --version 1.0 --model-file ./serve/examples/image_classifier/densenet_161/model.py --serialized-file densenet161-8d451a50.pth --export-path model_store --extra-files ./serve/examples/image_classifier/index_to_name.json --handler image_classifier`

And to run this in docker just prepend RUN so `RUN torch-model-archiver` etc...

As far as your second issue goes `torchserve` is installed on the Docker instance by default so it shouldn't be interacting with your local torchserve instance https://github.com/pytorch/serve/blob/master/docker/Dockerfile#L66

if you're still running into lots of permission issues just change the user here to root https://github.com/pytorch/serve/blob/master/docker/Dockerfile#L101

**Comment by msaroufim** [comment]
Talked offline - there are some confusing aspects in our Dockerfile
`model_store` and `config.properties` are not owned by the `model-server` user but owned by root - doing a straight `chown` didn't work either, we need to look more carefully at the script and how ownership works when new directories are created

As a workaround we logged into the Docker container, stopped torchserve, created a new model_store, downloaded the weights from the mar and then things worked

Super important to revisit our Dockerfiles to make sure noone goes through this pain again

**Comment by jagadeeshi2i** [comment]
@ytsheng 

1. Pls check that you are not mounting a root owned local path to docker container as volume. Try running docker container from `serve` folder and check if you are still facing the issue. Make sure ts is cloned to non root path.
2. The second issue is, you trying run torchserve from `pytorch/dev:latest` image.

**Comment by akiross** [comment]
@msaroufim, we are experiencing similar issues due to permissions using serve with containers. The fixes are easy, but it doesn't work out of the box. I'm writing to suggest that, maybe, it's also worth to ensure that torch serve Dockerfile might run on other platforms with non-standard configurations, for example rootless docker or rootless podman containers.
