### ISSUE TITLE
Nightly S3 bucket for torchserve in pytorch.org

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1330]
## Problem

As of now torchserve does nightly builds using AWS code build https://github.com/pytorch/serve/tree/master/ci but we don't have any nightly place to upload them. Our top priority is to make nightly builds available in an S3 bucket like `https://download.pytorch.org/whl/torchserve` with a url under the `pytorch.org` domain. Pypi and conda nightly builds are lower priority.

### New S3 bucket
One solution would be to setup a new public S3 bucket under the Pytorch account and give write privileges for a torchserve team canonical ID that would allow aws codebuild to push nightly binaries to the bucket

Recommendation is NOT to allow write access to existing S3 bucket since that's a security risk

### CircleCI or Github Actions migration
Another approach may be to move build and upload to circle CI and github actions from codebuild which would let us also support sharing nightly builds on pypi and conda

FYI: @seemethere @nskool @lxning @HamidShojanazeri 

![image](https://user-images.githubusercontent.com/3282513/142293012-6744214e-c156-45df-9d57-99bb9b0d9fd8.png)

**Comment by seemethere** [comment]
I think given the simplicity of the build pipeline it makes sense to create a new GHA workflow that uploads to our existing S3 bucket for `download.pytorch.org`

**Comment by malfet** [comment]
Perhaps its a time for a great BE effort (and reducing security risk): what if nightly builds are published as GH artifacts and some sort of lambda on AWS will scan selected projects and re-publishes them to download.pytorch.org?
Also, correct me if I'm wrong, but given the frequency of torchserve changes, there is no need for the actual nightly builds? (I.e. even master commit can sort of update the build, can it?)

**Comment by msaroufim** [comment]
@seemethere regarding a new GHA workflow, would that mean that GHA actions would manage secrets? A similar story shows up in torchX where they have their secret setup and automatic promotion to pypi https://github.com/pytorch/torchx/blob/main/.github/workflows/nightly.yaml - I'd imagine nothing is stopping us from doing this now and that we as a next step do what @malfet is suggesting with pushing GH artifacts to `downloads.pytorch.org`

We definitely do need nightly builds, especially when fixing bugs it's super frustrating for users to have to wait for an official release.

**Comment by nskool** [comment]
> I think given the simplicity of the build pipeline it makes sense to create a new GHA workflow that uploads to our existing S3 bucket for `download.pytorch.org`

@msaroufim and I had an offline discussion about the nightly builds summarized below:

Hi @seemethere @malfet could you provide more information on how we can upload the nightly *.whl files to download.pytorch.org?

Here's the setup we currently have:
1. We upload the binary to an S3 bucket using the spec here: https://github.com/pytorch/serve/blob/master/ci/torchserve_nightly_build.yml#L20.
2. We then front the S3 bucket by AWS Cloudfront, thereby creating a URL such as this: http://d2m4sil2y6pyx8.cloudfront.net/whl/nightly/torch_model_archiver-0.5.1-py2.py3-none-any.whl.
3. In this case - `discoverability` of other packages is a problem, since each object is public but the entire bucket is not, so users cannot simply browse the packages hosted at the path http://d2m4sil2y6pyx8.cloudfront.net/whl/nightly/*.


Where we'd like to get to:
1. Build the binaries on a nightly basis (infra already in place on codebuild, but can be moved to github actions easily).
2. Upload them to an index on download.pytorch.org, similar to https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html. 
3. Such an URL would look like https://download.pytorch.org/whl/nightly/cpu/torchserve_nightly.html, and users can then use the package as `pip install --pre torchserve -f https://download.pytorch.org/whl/nightly/cpu/torchserve_nightly.html`
4. Note that torchserve does not have different packages for CPU/GPU and therefore the sub-pages on download.pytorch.org could differ than the above exact URL.

For this purpose, is there an existing setup that we can refer/re-use on github actions? How do you recommend going about this?

**Comment by msaroufim** [comment]
Hi @malfet @seemethere did you get a chance to take a look at @nskool's question above?

**Comment by nskool** [comment]
Hi @seemethere @malfet - curious about your thoughts on how we can proceed.

**Comment by nskool** [comment]
Hi @seemethere @malfet 

Do you think this script could be useful https://github.com/pytorch/pytorch/blob/master/.circleci/scripts/binary_upload.sh (but would run in GHA instead on pytorch/serve repo)

Specifically, could you create a bucket on your end, that could replace the bucket here - https://github.com/pytorch/pytorch/blob/master/.circleci/scripts/binary_upload.sh#L15. I can write the script, just request you to create the bucket, or suggest an existing one.

I can perhaps then upload the nightly binary to this bucket. (and you could arrange for the necessary permissions to do so).
