### ISSUE TITLE
Docker image (dev) size is too large - 13GB

### ISSUE THREAD

**Issue by rashmikaslikar** [pytorch/serve#1420]
Hello everyone,
I used the torchserve docker file as it is to build a docker image of type dev on a machine with fresh docker installation. The size of this image is 13.3 GB which is too large. Any insights on why this is the case will be very helpful. I use the TorchServe version 0.5.2. Thank you for your kind help.
Best,
Rashmi

**Comment by msaroufim** [comment]
Hi @rashmikaslikar it seems like the average docker image size is around 2GB on CPU and 4GB on GPU https://hub.docker.com/r/pytorch/torchserve/tags

I haven't spent too much time optimizing the dev docker image but likely culprits are needing to install Java dependencies https://github.com/pytorch/serve/blob/master/docker/Dockerfile.dev#L73

Dev dependencies also include a larger `requirements.txt`, node dependencies, brew dependencies which could be the cause of the bloat you're seeing https://github.com/pytorch/serve/blob/master/ts_scripts/install_dependencies.py#L150

I'd be happy to spend time removing some of the bloat but could you give me a better idea of why it's important to remove it so I can prioritize?

**Comment by rashmikaslikar** [comment]
Hi @msaroufim thank you very much for your quick reply. 
So the bloat in the image size is because of the need to install a lot of dependencies. Is this the case only for a development image? My concern for the large image size was the space it consumes and the limitations it brings when I want to share the docker container with others.  Will a production docker image be much smaller in size? Right now I am in the development phase of my project, but in the near future I will be deploying the model into production. Thank you for your kind help :)
Best,
Rashmi

**Comment by msaroufim** [comment]
Hi @rashmikaslikar yes exactly. If you're deploying torchserve you should not be using the dev docker environment and instead use the regular one. The dev one is bloated because it makes development simpler for the core team where we mostly develop on machines where 13GB isn't a huge issue.

But if you're deploying to prod make sure to use these images as a starting point https://hub.docker.com/r/pytorch/torchserve (the sizes there are between 2-4GB depending on whether you're using a GPU or not)

Happy to help and let me know if you have any more questions!

**Comment by rashmikaslikar** [comment]
Thanks a lot @msaroufim
