### ISSUE TITLE
Model analyzer

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/serve#1438]
### Problem
Currently users have to run the benchmark suite and do an exhaustive search to find the optimum batch size, number of workers, concurrency, etc., this solution is not scalable and need guidance throughout the process. 

### Proposed feature
Having a model analyzer that take a mar file and profiles the model and run benchmark on search space in an optimized way and give suggestions/ report to user to make an informed decision over different parameters. It may also suggest optimizations present in Torch_prep as well.

CC: @gchanan , @msaroufim

**Comment by msaroufim** [comment]
Funnily enough, I did try to brute force this for a BERT model and my job was running for over 2 days with a modest number of hyperparameters and even then it wasn't entirely clear to me what the right configuration should be. Even once I had the giant spreadsheet I wasn't entirely sure how to read it since my eyes aren't that great at making sense of `n-dimensional problems. So naive grid search just doesn't work all that great especially if you're iterating on several models - cc @d4l3k who may have thought about these kinds of problems working on HPO for training

This is an area where I think doing a parallelized search in a cloud-native way actually really helps to get results in a more reasonable way. The user would configure some max allowable AWS budget that would limit for how long you can search for and given that budget find the optimal latency or throughput depending on whether application is online or offline. And the output would be a report that's easy to parse not just raw csv.

```
Find optimal latency or throughput
S.t AWS spend < $X
```

Even in the trivial setting where you just brute force a bunch of `for loops` and then write data to disk users need to think about cold start problems, how statistically significant a change is so the expectation to run PyTorch in production is pretty much "go build a benchmarking suite with all the nuance it implies". Benchmarking is hard that's why we need projects like MLPerf to make comparisons clearer and aggregate common gotchas, feels like an area we should be more opiniated in.

**Comment by HamidShojanazeri** [comment]
thanks @msaroufim, sure that's a good idea to discuss and come up with a good design/ affordable approach, there are solutions on [Sagemaker](https://aws.amazon.com/about-aws/whats-new/2021/12/amazon-sagemaker-inference-recommender/) and [triton](https://github.com/triton-inference-server/model_analyzer) that we might be able to learn lessons from.

**Comment by msaroufim** [comment]
Also FYI @yqhu since we've had a similar related discussion on the importance of profiling tools to make something like this possible

**Comment by msaroufim** [comment]
Wrote an RFC https://github.com/pytorch/serve/issues/1457

**Comment by msaroufim** [comment]
Dup
