### ISSUE TITLE
How to properly understand MaxBatchDelay

### ISSUE THREAD

**Issue by Hegelim** [pytorch/serve#1699]
From the documentation https://github.com/pytorch/serve/blob/master/docs/management_api.md#register-a-model
The parameter `maxBatchDelay` is the maximum delay for batch aggregation. It will wait this amount of time before aggregating all the requests (please correct me if I am wrong) into batches. Now, on the user side, if I set this number high, like 5000, then TorchServe will have enough time to receive possibly a large number of requests, then aggregates them. However, a large number like 5000 also means that the total time for the user to send requests and receive inference results will also be higher, and much higher if I set this number to 50. A user/client for sure wants to have as little time as possible before having the results, but setting maxBatchDelay low would also mean TorchServe wouldn't have enough time to aggregate. 

How to properly understand this issue? Do I need a better metrics to measure the total time for the client, or should I set maxBatchDelay high? Or something else?

**Comment by msaroufim** [comment]
> The parameter maxBatchDelay is the maximum delay for batch aggregation. It will wait this amount of time before aggregating all the requests (please correct me if I am wrong) into batches. 

That is correct

> A user/client for sure wants to have as little time as possible before having the results, but setting maxBatchDelay low would also mean TorchServe wouldn't have enough time to aggregate.

`maxBatchDelay` or `batch_size` more generally in inference is a tradeoff between latency and throughput. If what you care about is the maximum time it takes to return an inference for a single request then you should opt for smaller batch sizes e.g `batch_size = 1`. However if you care more about throughput or your GPU utilization then you go faster on a group of requests because you're processing a whole batch but an inference for an individual element will be slower.

Typically what you should pick is more application dependent so if for example you have an ML model where the most important thing is getting back to a user quickly otherwise they will go a different website then you're in the real time inference camp. Otherwise if a user is not waiting for a result then you're better off having a larger batch size to better utilize your GPU.

**Comment by violetcodes** [comment]
Please help me understand from an LLM serving perspective. A single request to generate text with 7b/13b llm may take 2-3 seconds (if we are generating 200-300 tokens). So we should always deploy llms with batch_size > 1 and a reasonable delay (maybe 0.5 s), otherwise in batch_size=1 serving, requests which are less than 0.5 sec apart would experience about 2x or more latency. Is this correct?
