### ISSUE TITLE
Support for KServe V2 gRPC Prediction API?

### ISSUE THREAD

**Issue by njhill** [pytorch/serve#1859]
I've seen that TorchServe [now supports](https://github.com/pytorch/serve/pull/1190) the [KServe V2 Prediction API](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2) but as far as I can see, this is only the REST flavour of it, via the `kservev2` service envelope.

Are there any plans to add support for the [gRPC version](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#grpc) of this API? If not, could it be considered?

While there's been [integration of TorchServe with KServe "classic"](https://kserve.github.io/website/modelserving/v1beta1/torchserve/) for some time, I'm currently [adding](https://github.com/kserve/modelmesh-serving/issues/63) an integration of it with [ModelMesh Serving](https://github.com/kserve/modelmesh-serving) which is a newer addition to KServe for high-density use cases, managing the dynamic loading/unloading of multiple models per process.

ModelMesh handles the routing of inference requests in this case, but it currently only supports gRPC. This means it will only be usable initially with TorchServe's [native gRPC inference API](https://pytorch.org/serve/grpc_api.html), but it would be great if the KServe API could be supported too to bring parity with the other supported model servers (Nvidia's Triton, Seldon's MLServer, Intel's OpenVINO Model Server).

**Comment by yuzisun** [comment]
+1, the KServe python SDK 0.10 added support for KServe's gRPC inference protocol and TorchServe already uses it as the wrapper, I hope it should be pretty straight forward to get TorchServe to support this.

**Comment by yuzisun** [comment]
cc @jagadeeshi2i @chauhang

**Comment by sakoush** [comment]
This will enable the integration of TS as a backend in Seldon Core [v2](https://github.com/SeldonIO/seldon-core/tree/v2), which implements the v2 protocol similar to kserve. 

Given that TS already supports v2 REST inference, it would be great if GRPC v2 dataplane inference is added as well. In Seldon Core v2 we rely on GRPC inference for many of data-centric features we have for performance reasons.

**Comment by msaroufim** [comment]
@jagadeeshi2i I think the high level approach seems reasonable, would you be able to lead on this?

**Comment by jagadeeshi2i** [comment]
sure @msaroufim

**Comment by yuzisun** [comment]
@jagadeeshi2i @msaroufim Currently torchserve uses the KServe python server in front of the TorchServe Netty server, I think this extra layer provides very little value and cause a lot of the issues. The KServe python SDK is mainly designed for native python inference runtimes when user wants to implement arbitrary inference code with pre/post processing, TorchServe also provides similar custom handlers, so there are no good reasons why we need both and have all the kserve inference requests going through `kserve python server -> Netty -> torchserve python worker`.  Since KServe now has [open inference protocol specification](https://github.com/kserve/open-inference-protocol), can we implement OIP natively in torchserve like other model servers ?
