### ISSUE TITLE
Torchserve vs plain model inference

### ISSUE THREAD

**Issue by frankiedrake** [pytorch/serve#1985]
I'm currently working on a project that is running under gunicorn and performs an inference on a `speechbrain` model with some audio data. The model size is about 80Mb and the inference is performed each 5 minutes with 50-100 number of  files, 30secs each (I use a batch of 4 audios). Everything works well under docker on my local machine, but on a production environment (where docker container is running on a virtual machine) there's high CPU and memory consumption so my app is killed by OOM-killer about two times a day.

Seems like I tried everything I could, followed performance tuning guides and nothing changed (except of adding the usage of LD_PRELOAD taken from [here](https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html) - seems application started to behave better after adding this library, it was killed much more often before).

**So my question is**, if I have only one model, will I have some significant performance / resource management improvement launching my model under `torchserve`? Or, maybe, I can apply some techniques from torchsrve to my application to get advantage of it?

**Comment by msaroufim** [comment]
Hi @frankiedrake there's many aspects to your question
* Since you got everything to work fine in a docker environment the most likely culprit for why you're seeing issues is mostly how you've setup your VM. So it's helpful to run something like `nvidia-smi` in a loop along with some logs to figure out when the OOM is occuring and what was going on then
* Tuning the performance of pytorch models has a lot of solutions whether it's CPU tuning or setting some environment variables or using a model optimization runtime like ONNX or TensorRT. 
* Oftentimes the issue is not necessarily just your model but also other memory that's allocated maybe the audio files aren't of even sizes, maybe some batches are too big, maybe some memory is not being freed after an inference is done. This is where profiling really helps whether its the PyTorch profiler or Nsight or other tools like `py-spy`
* Resource management is tricky, even with a single model you will need multiple workers for added parallelism but each worker will need its own memory and CUDA context which is necessary bloat until you integrate something like pytorch/multipy

torchserve is focused on multi model inference but there's a lot of side problems we handle for you if you don't want to think about them including all of the above. Of course would need to learn more about the specifics of your problem but a high level I think some logging would unblock you for now.

**Comment by frankiedrake** [comment]
Hi, @msaroufim big thank for a quick response.
Considering `onnx` and `torchscript`, I've spent a lot of time trying to get it to use, but, it didn't work out-of-the box, `torchscript` - quantization gives a model of size 20Mb, but exporting it to torchscript requires rewriting a lot of code, as for onnx convertion (using `torch.onnx.convert`), it didn't gave any boost (not in size, not in inference time), sure, I could try digging deeper, trying native onnx quantization, etc), but I think it's a redundant overhead, cause it works well in general way and the problem occures only on docker under the VM (as you say it's probably a culprit) so I should focus on other aspects of the realization.

Thank you for profiling suggestions, though production environment is set by devops, I'll see what I can do.

And if you say that torchserve does a lot of optimization work, I'll consider trying to get it to use.
