### ISSUE TITLE
TorchServe support model tgz format

### ISSUE THREAD

**Issue by lxning** [pytorch/serve#2213]
### 🚀 The feature

 TorchServe is able to decompress tgz format model generated by torch-model-archiver [option  --archive-format](https://github.com/pytorch/serve/tree/master/model-archiver#arguments)

### Motivation, pitch

torch-model-archiver supports tgz format. However, existing TorchServe is not able to decompress tgz format model.

**Comment by HamidShojanazeri** [comment]
Thanks @lxning for the PR, I suggest we add a doc for the usage and link it in the very front page to point users that they would be able to use `tgz` format instead of `mar` file. 

This can benefit user from a size reduction in the packaged file (mar file) and also its more familiar to the user.

Also,  as discussed user is able to pass a `path_to_model_checkpoints` instead of zip file in the `torch-model-archiver --model-name bloom --version 1.0 --handler handler.py --extra-files model.zip`
