### ISSUE TITLE
Captum installation breaks torchserve dependency installation

### ISSUE THREAD

**Issue by agunapal** [pytorch/serve#2358]
### 🐛 Describe the bug

Currently torchserve installs captum by default.
captum ends up installing dependencies which take around 2GB of space.

Hence, this should be optional

### Error logs

NA

### Installation instructions

Using Docker

### Model Packaing

NA

### config.properties

NA

### Versions

0.8.0

### Repro instructions

Pull the latest docker image

**Comment by mreso** [comment]
Seems like the issue is not that the direct captum dependencies are too big but captum gets installed before torch while torch is a dependency of captum. This basically triggers `pip install torch` which leads to installation of GPU torch even in the CPU image. The solution should thus will be to install captum after installing torch.

**Comment by agunapal** [comment]
This solution sounds good as a short term solution . But, going forward to simplify last minute issues on releases etc, we want to keep torchserve as lean as possible. Have only the required libraries for most users
