### ISSUE TITLE
Remove home folder paths from README.md

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#268]
Two distinct issues here:

Before #248, there were `~` on some of the paths in quick start commands, but not on at least one other. #248 updated the file to be consistent, with `~`.

The problem is that this is wrong. We don't want to prescribe doing this in anyone's home folder. The `~` path specifiers should be removed.

**Comment by aaronmarkham** [comment]
It was made to be consistent because if you want people to be able to copy and paste the commands to start up the server you need to specify the model store location. This needs to be somewhere. Rather than spend a bunch of instruction on this the home folder is used by default since it is arguably easier to test out. 

Unless some location for the model store is defined and used throughout, I would vote to keep the examples using the home folder.

**Comment by fbbradheintz** [comment]
I would change every `~` to a `.` - that changes it from "do it in your home directory" to "do it in your current directory" - the different being that if a user *doesn't* want to do it in `~` (I know mine is pretty cluttered), they then have to go and change *every* `~`-containing command line that we provide them - the cut-and-paste runthrough is no longer an option. Changing to `.` works everywhere, including the home directory.

**Comment by eslesar-aws** [comment]
Submitted https://github.com/pytorch/serve/pull/292 to address this.

**Comment by fbbradheintz** [comment]
> Submitted #292 to address this.

Reviewing now.

**Comment by fbbradheintz** [comment]
Reopening - still tweaks to be made
