### ISSUE TITLE
Broken example for a custom Counter metrics

### ISSUE THREAD

**Issue by feeeper** [pytorch/serve#2978]
### 📚 The doc issue

The example in the section [Add Counter based metrics](https://github.com/pytorch/serve/blob/18d56ff56e05de48af0dfabe0019f437f332a868/docs/metrics.md#add-counter-based-metrics) shows how to add custom Counter metric:
```
# Create a counter with name 'LoopCount' and dimensions, initial value
metrics.add_counter('LoopCount', 1, None, dimensions)

# Increment counter by 2 
metrics.add_counter('LoopCount', 2 , None, dimensions)

# Decrement counter by 1
metrics.add_counter('LoopCount', -1, None, dimensions)
```

I tried to copy this example to my custom handler:
```
dims = [Dimension('ModelName', 'doc_model')]
self.metrics.add_counter('LoopCount', 1, None, dimensions=dims)
# Increment counter by 2 
self.metrics.add_counter('LoopCount', 2 , None, dimensions=dims)
# Decrement counter by 1
self.metrics.add_counter('LoopCount', -1, None, dimensions=dims)
```

When I call API for inference I got an error in the terminal:
```
2024-02-28T15:23:57,011 [ERROR] W-9000-doc_model_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Failed to parse metrics line: "[METRICS]Failed to update metric with name:LoopCount and dimensions: ModelName:doc_model,Level:Model with value: -1: Counter metric update value cannot be negative".
```

**Comment by namannandan** [comment]
@feeeper This error is expected since `counter` metrics cannot have negative values. You will need to use a `gauge` metric for this use case by setting `metric_type = MetricTypes.GAUGE`: https://github.com/pytorch/serve/blob/v0.9.0/docs/metrics.md#function-api-to-add-generic-metrics-with-default-dimensions.

Torchserve metrics are modeled based on prometheus metrics semantics: https://prometheus.io/docs/concepts/metric_types/

A more detailed examples to emit various types of custom metrics: https://github.com/pytorch/serve/tree/master/examples/custom_metrics

**Comment by feeeper** [comment]
@namannandan yeah, I got it. By what I want to say that I got this _exact code snippet_ from your documentation. And this snippet doesn't work.

**Comment by namannandan** [comment]
Metrics documentation will be fixed as a part of this tracking issue: https://github.com/pytorch/serve/issues/3001
