### ISSUE TITLE
Unable to install on GPU machine

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#30]
`pip install .` command failed with errors when installing on a ubuntu 18.04 GPU server (aws p3.8xlarge). The gradle tests as part of the  install are failing with many `Backend worker monitoring thread interrupted or backend worker process died` errors in the logs. 

Error logs are attached.
[error.txt](https://github.com/pytorch/serve/files/4209229/error.txt)

**Comment by josiahdavis** [comment]
I am still experiencing the same issue/error as @chauhang (running `./build_image --gpu` on an Ubuntu 18.04 EC2 Instance `m4.xlarge`).
 
<img width="1435" alt="Screenshot 2020-05-21 at 5 02 56 PM" src="https://user-images.githubusercontent.com/6405428/82542654-f2d11b00-9b84-11ea-9f8a-e1d2c6540257.png">

**Comment by harshbafna** [comment]
@josiahdavis : The original issue was related to installing torchserve from source on a GPU based EC2 instance like p3.2xlarge.

In your case this is related to the error observed while creating the docker image for GPU. 

Could you please create a new issue for this with details in this format :

## Context


* torchserve version:
* torch version:
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version:

## Your Environment

* Installed using source? [yes/no]:
* Are you planning to deploy it using docker container? [yes/no]:
* Is it a CPU or GPU environment?:
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?:
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior


## Current Behavior


## Possible Solution


## Steps to Reproduce


1.
2.
...

## Failure Logs [if any]
