### ISSUE TITLE
Serialize models to store in DDB

### ISSUE THREAD

**Issue by mycpuorg** [pytorch/serve#362]
To allow for scaling of snapshots across server instances. [Snapshot Serialization](https://github.com/pytorch/serve/blob/376110010a2fe3f8341d6299ec60795eaead7bf6/frontend/server/src/main/java/org/pytorch/serve/snapshot/SnapshotSerializerFactory.java#L7) should allow for database storage such as DynamoDB. This must be made optional through config properties since most customers may not use such an option.

**Comment by mycpuorg** [comment]
@dhaniram-kshirsagar thoughts?

**Comment by dhaniram-kshirsagar** [comment]
> @dhaniram-kshirsagar @harshbafna thoughts?

At a high level -
- The credential for DDB client will be available via [Default Credential Provider Chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html)
- Table will be added/dropped in DDB via script [use best practice] (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/best-practices.html) to implement this]. This should be kept separate since user may not give permissions to create/alter schema at runtime.
- Snapshot data will be serialized/deserialized via [ddb Item apis](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html)
- 'Strongly Consistency Read' can be used for GetItem i.e. restoring a snapshot
- Local DDB mode support for local debugging/testing
- Need to define policy [based on duration to keep etc.] for snapshot cleanup
- Config param to switch between DDB/FS etc.

Assumptions - 
- AWS SDK jar for DDB will be added to build [check if same can be made conditional]
- AWS DDB operational aspects i.e. data security, backup/recovery, monitoring of the table will be taken care by end-user admin

**Comment by dhaniram-kshirsagar** [comment]
@mycpuorg Can you share your feedback on this.

**Comment by mycpuorg** [comment]
@dhaniram-kshirsagar This sounds good to me, in addition:

- Atomicity of save and restart operations (Which is the reason DDB is suitable)
- DDB ops have to be completely outside the scope of this and logs should indicate failures
- as a POC it's worth benchmarking mounting a remote FS on a local path (such as EBS)

@maaquib was interested in this too?

**Comment by mycpuorg** [comment]
@dhaniram-kshirsagar this sounds good. Please proceed and make a PR. Thanks.

**Comment by dhaniram-kshirsagar** [comment]
> * DDB ops have to be completely outside the scope of this and logs should indicate failures

Can you please elaborate on this?
