### ISSUE TITLE
Cannot create model archive in waveglow example

### ISSUE THREAD

**Issue by jagadeeshi2i** [pytorch/serve#761]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context
While creating model archive file for waveglow example the create_mar.sh script fails with 404 error.

```
+ wget https://api.ngc.nvidia.com/v2/models/nvidia/tacotron2pyt_fp32/versions/1/files/nvidia_tacotron2pyt_fp32_20190306.pth
--2020-10-29 15:08:01--  https://api.ngc.nvidia.com/v2/models/nvidia/tacotron2pyt_fp32/versions/1/files/nvidia_tacotron2pyt_fp32_20190306.pth
Resolving api.ngc.nvidia.com (api.ngc.nvidia.com)... 54.213.120.107, 54.186.38.188
Connecting to api.ngc.nvidia.com (api.ngc.nvidia.com)|54.213.120.107|:443... connected.
HTTP request sent, awaiting response... 404 
2020-10-29 15:08:02 ERROR 404: (no description)
```

* torchserve version:
* torch version:1.6.0
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version: Ubuntu 16.04 64bit

## Your Environment
* Installed using source? [yes/no]:no
* Are you planning to deploy it using docker container? [yes/no]:yes
* Is it a CPU or GPU environment?:GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?:audio
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Possible Solution
Fix the broken links

## Steps to Reproduce

1. Navigate to waveglow example in torchserve
2. Run create_mar.sh script
...

**Comment by alvarobartt** [comment]
Hi @jagadeeshi2i! I'm currently working on a PR to solve this as the NVIDIA models URL has been updated so some changes need to be done on that script.

**Comment by alvarobartt** [comment]
@harshbafna I just saw that you self-assigned this, you want me to keep on working on the PR or should I discard it? Thanks!

**Comment by harshbafna** [comment]
@alvarobartt: If you are already working on this and found the fix please continue and feel free to submit the PR :-)

I just checked that this is a known issue in `NVIDIA/DeepLearningExamples` repo. The Tacotron2 model which is used in this example is not available on `torch.hub` anymore:

Ref: 

https://github.com/NVIDIA/DeepLearningExamples/issues/725
https://github.com/NVIDIA/DeepLearningExamples/issues/721

**Comment by alvarobartt** [comment]
Sure @harshbafna! I'll try to fix it now!

**Comment by alvarobartt** [comment]
The issue seems to be related with a model update NVIDIA did, which somehow removed/deleted the previous model, so the specified version of that model couldn't be found at [NVIDIA Catalog - Models](https://ngc.nvidia.com/catalog/models?orderBy=modifiedDESC&pageNumber=1&query=&quickFilter=models&filters=).

On the other hand, both Tacotron2 and Waveglow models are available, but the version of those models is a more updated one than the one defined in the `create_mar.sh` script. Now the availability of those models (with the same configuration as the one used on the previous ones) is as it follows:
- __Tacotron2__ checkpoint can be found at https://ngc.nvidia.com/catalog/models/nvidia:tacotron2_pyt_ckpt_fp32 and the model (.pth) can be found at https://ngc.nvidia.com/catalog/models/nvidia:tacotron2_pyt_ckpt_fp32/files, as it figures as a separate file on the File Browser tab.
- __Waveglow__ checkpoint can be found at https://ngc.nvidia.com/catalog/models/nvidia:waveglow_ckpt_fp32 and the model (.pth) can be found at https://ngc.nvidia.com/catalog/models/nvidia:waveglow_ckpt_fp32/files, as it figures as a separate file on the File Browser tab.

So that the `create_mar.sh` script has been updated with the new model URLs, anyway I will create the PR now so as to check whether the tests pass or not. In case that the tests work I'll also resolve the other issues you send me as a reference!

**Comment by chauhang** [comment]
@alvarobartt Please also add the related requirements.txt file for the waveglow example so that the pip install dependencies get picked up by TorchServe for running the models.

**Comment by alvarobartt** [comment]
Hi @chauhang, I included the Waveglow requirements into the `create_mar.sh` file as you can see at: https://github.com/alvarobartt/serve/commit/0bbe4bfcc18fec498950f44feeec5105b60fb958, should I instead create a `requirements.txt` file and then `pip install -r requirements.txt` or is it ok to leave it just like that? Thank you! 👍🏻

**Comment by harshbafna** [comment]
@alvarobartt: Yes, please move the python packages to a `requirements.txt` file and include it as part of `torch-model-archiver` command instead of adding a pip install command. This way user will not require to install the custom python packages on the server manually while deploying the model on TorchServe. TorchServe automatically installs the packages specified in the requirements.txt file in the model-archive if the [install_py_dep_per_model](https://github.com/pytorch/serve/blob/master/docs/configuration.md#allow-model-specific-custom-python-packages) flag is set to true in the server configuration.

**Comment by alvarobartt** [comment]
Hi @harshbafna, thanks for the tips! Honestly I was not aware of that feature regarding the `torch-model-archiver` package. I'll update this ASAP 👍🏻

**Comment by alvarobartt** [comment]
Already updated #762 🤗 @harshbafna @chauhang
