### ISSUE TITLE
Add examples for HuggingFace models

### ISSUE THREAD

**Issue by adityabindal** [pytorch/serve#85]
Create examples or tutorials to show how to deploy HuggingFace PyTorch models with TorchServe

**Comment by MFreidank** [comment]
I put together a blog post to showcase how to write custom handler code for a simple huggingface BERT sentence classifier:
https://medium.com/@freidankm_39840/deploy-huggingface-s-bert-to-production-with-pytorch-serve-27b068026d18

Let me know if I can be of any help in putting together an example or some documentation around this topic.

**Comment by chauhang** [comment]
Added by PR #302

**Comment by ehutt** [comment]
Hi - I wrote a custom model handler for serving a Hugging Face transformers T5 model for text generation. I did not find any existing examples that worked due to some slight differences between T5 and other transformers in the library. Where would be the best place to contribute this model handler example? Thanks and apologies if this is not the right place for this question.

**Comment by ekaterinatretyak** [comment]
@ehutt 
> Hi - I wrote a custom model handler for serving a Hugging Face transformers T5 model for text generation. I did not find any existing examples that worked due to some slight differences between T5 and other transformers in the library. Where would be the best place to contribute this model handler example? Thanks and apologies if this is not the right place for this question.

Hi,
Could you kindly share you code for serving a hugging face T5 model?

**Comment by ndvbd** [comment]
> [ehutt](/ehutt)

Ehutt, Can you share the code here?
